version: "3.8"
services:
  the-sentinel:
    build: .
    container_name: the-sentinel
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "start"]
